// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pagination.Data;

namespace pagination.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220205201629_AddSeedDataToUsers")]
    partial class AddSeedDataToUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("pagination.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 167, DateTimeKind.Local).AddTicks(6918),
                            Family = "Nojoumy",
                            Name = "Mohammad"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(6799),
                            Family = "Saei",
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(6960),
                            Family = "Rezaei",
                            Name = "Hosein"
                        },
                        new
                        {
                            Id = 4,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(6987),
                            Family = "Khani",
                            Name = "Arash"
                        },
                        new
                        {
                            Id = 5,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7009),
                            Family = "Sami",
                            Name = "Saeed"
                        },
                        new
                        {
                            Id = 6,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7026),
                            Family = "Ghari",
                            Name = "Sahar"
                        },
                        new
                        {
                            Id = 7,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7050),
                            Family = "Samiei",
                            Name = "Shima"
                        },
                        new
                        {
                            Id = 8,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7066),
                            Family = "Bahari",
                            Name = "Zahra"
                        },
                        new
                        {
                            Id = 9,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7084),
                            Family = "Asghari",
                            Name = "Fatemeh"
                        },
                        new
                        {
                            Id = 10,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7102),
                            Family = "Abdi",
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = 11,
                            Age = 21,
                            CreateDate = new DateTime(2022, 2, 5, 23, 46, 28, 184, DateTimeKind.Local).AddTicks(7120),
                            Family = "Irani",
                            Name = "Hanie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
